"""add is_active to tank

Revision ID: c5f44fd624d5
Revises: 
Create Date: 2026-08-18 11:18:25.696088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f44fd624d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
      'tanks', 
      sa.Column('is_active', 
      sa.Boolean(), 
      nullable=False,
      server_default=sa.true()
      ))

    op.alter_column(
      'tanks',
      'is_active',
      server_default=None
      )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanks', 'is_active')
    # ### end Alembic commands ###
