"""add user verification status

Revision ID: d71a58f1bebd
Revises: b16dd134a8f0
Create Date: 2026-09-08 20:31:07.160504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71a58f1bebd'
down_revision: Union[str, Sequence[str], None] = 'b16dd134a8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f('ix_smart_farm_os_public_id'), 'smart_farm_os', ['public_id'], unique=True)
    # ### end Alembic commands ###

    op.alter_column(
        'User',
        'is_verified',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_farm_os_public_id'), table_name='smart_farm_os')
    op.drop_column('User', 'is_verified')
    # ### end Alembic commands ###
